INSERT INTO categories (name)
VALUES ('Electronics'),
       ('Groceries'),
       ('Beverages'),
       ('Personal Care'),
       ('Home & Kitchen'),
       ('Snacks'),
       ('Office Supplies'),
       ('Fitness'),
       ('Pet Supplies'),
       ('Books');

INSERT INTO products (name, price, description, category_id)
VALUES ('Apple AirPods Pro (2nd Generation)',
        249.99,
        'Wireless noise-cancelling earbuds with adaptive transparency and USB-C charging case.',
        1),
       ('Kirkland Organic Whole Milk',
        4.99,
        '1-gallon organic whole milk sourced from certified organic farms.',
        2),
       ('Coca-Cola Zero Sugar 12-Pack',
        8.49,
        '12 cans of Coca-Cola Zero Sugar soft drink with no calories.',
        3),
       ('Dove Deep Moisture Body Wash',
        6.99,
        'Moisturizing body wash formulated for soft and healthy skin.',
        4),
       ('Instant Pot Duo 7-in-1 6QT',
        89.99,
        'Multi-use pressure cooker with slow cook, steam, rice cook, and sauté functions.',
        5),
       ('Oreo Original Cookies Family Pack',
        5.49,
        'Classic chocolate sandwich cookies with vanilla creme filling.',
        6),
       ('Pilot G2 Premium Gel Pen Pack (12 Count)',
        11.99,
        'Smooth-writing retractable gel pens with long-lasting ink.',
        7),
       ('Optimum Nutrition Gold Standard Whey Protein',
        34.99,
        'Vanilla flavored whey protein powder designed for muscle recovery and fitness.',
        8),
       ('Purina Friskies Dry Cat Food',
        12.99,
        'Seafood flavored dry cat food for adult cats.',
        9),
       ('Atomic Habits',
        18.99,
        'Popular self-improvement book by James Clear focused on building better habits.',
        10);